name: Add Contributor on Merge

on:
  pull_request:
    types: [closed]

jobs:
  add-contributor:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Add contributor to list
        uses: all-contributors/actions/add@v1
        with:
          path: .all-contributorsrc
          bot-token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
